CREATE TABLE EMPLOYEES
(
    employee_id       NUMBER
        GENERATED BY DEFAULT AS IDENTITY START WITH 1
    PRIMARY KEY,
    first_name      VARCHAR2(50) NOT NULL,
    last_name       VARCHAR2(50) NOT NULL,
    telephone       VARCHAR2(20) NOT NULL,
    e_mail          VARCHAR2(75),
    address         VARCHAR2(250) NOT NULL
)


--UNION
SELECT fýrst_name, last_name, telephone, e_mail, address from customers
union
select fýrst_name, last_name, telephone, e_mail, address from employees;

--UNION ALL
SELECT fýrst_name, last_name, telephone, e_mail, address from customers
union all
select fýrst_name, last_name, telephone, e_mail, address from employees;

--MINUS
SELECT fýrst_name, last_name, telephone, e_mail, address from customers
minus
select fýrst_name, last_name, telephone, e_mail, address from employees;


--INTERSECT
SELECT fýrst_name, last_name, telephone, e_mail, address from customers
intersect
select fýrst_name, last_name, telephone, e_mail, address from employees;


--INNER JOIN
select * from product p 
inner join category_ c on c.category_id=p.category_id;

--INNER JOIN
select * from customers cus 
inner join product p on p.product_id=cus.product_id
inner join category_ c on c.category_id=p.category_id;

--LEFT JOIN
select * from customers cus  
left join product p on p.product_id=cus.product_id
where p.product_id='601'


--INNER JOIN & LEFT JOIN
select * from customers cus  
inner join product p on p.product_id=cus.product_id
left join category_ c on c.category_id=p.category_id
where 1=1
and address ='ISTANBUL' 
and campaign = 'YES';


--FONKSÝYON ÖRNEKLERÝ
--1.Concat
select concat(first_name,last_name) as name_surname from customers; 

--2.Length
select length(segment_type) from category_;

--3.substr
select substr(product_model, 0, 2) from product;

--4.lpad
select lpad(telephone, 3) from employees;

--5.rpad
select rpad(segment_type, 3) from category_;

--6.lower &concat
select concat(lower(first_name),lower(last_name)) from customers;

--7.to_char
select * from customers
where to_char(date_, 'yyyy') in (2018)
and address ='KOCAELÝ'

--8.trim
select trim(trailing '0' from segment_type)  from category_;

--9.initcap
select initcap(address) from employees;

--10.lower
select lower(category_name) from category_;

--11.add_months
select date_, add_months(date_, 1) as add_1_month from customers;

--12.trunc
select trunc(price,-2) from product;

--13.round
select price, round(price,1) from product;

--14.ceil
select price, ceil(price) from product;

--15.rownumber
SELECT ROW_NUMBER() OVER(ORDER BY price DESC),product_model, price
FROM product;


